# Generated by Django 4.0.2 on 2022-02-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='duration',
            field=models.FloatField(default=0),
        ),
    ]
